version: '3.7'
networks:
  demo-apps:
    driver: bridge
services:
  frontend:
    container_name: vue-demo-app
    image: sesp13/vue-demo-app
    build: ./spa
    restart: unless-stopped
    ports:
      - 5000:80
    depends_on:
      - backend
    networks: 
      - demo-apps
  backend:
    image: sesp13/go-server:v2
    container_name: go-backend
    build: ./server
    restart: unless-stopped
    ports:
      - 4001:4001
    networks: 
      - demo-apps
